[package]
name = "ctx-bench"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ctx-bench"
path = "src/main.rs"

[dependencies]
ctx-core = { path = "../ctx-core" }
ctx-store = { path = "../ctx-store" }
ctx-index = { path = "../ctx-index" }
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile = "3"

[dev-dependencies]
base64 = "0.21"
fancy-regex = "0.13"
rustc-hash = "1"
tiktoken-rs.workspace = true
